language: cpp

# Compiler selection.
compiler:
  - clang
  - gcc

# Use Ubuntu 14.04 as the build environment.
sudo: required
dist: trusty

# Build dependencies.
# NOTE: Qt5 is not available on Ubuntu 14.04.
addons:
  apt:
    packages:
      - libpng-dev
      - libqt4-dev
      - libpcre3-dev

# Run the build script.
script: ./travis.sh

notifications:
  irc: "ircs://irc.badnik.zone:6697/#GensGS"
