language: cpp

# Compiler selection.
compiler:
  - clang
  - gcc

# Use Ubuntu 16.04 as the build environment.
# Ubuntu 14.04's qttools5-dev-tools is missing FindQt5LinguistTools.cmake.
sudo: required
dist: xenial

# Build dependencies.
addons:
  apt:
    packages:
      - libpng-dev
      - libpcre3-dev
      - qtbase5-dev
      - qttools5-dev-tools

# Run the build script.
script: ./travis.sh

notifications:
  irc: "ircs://irc.badnik.zone:6697/#GensGS"
