language: cpp

# Compiler selection.
compiler:
  - clang
  - gcc

# Use Ubuntu 14.04 as the build environment.
sudo: required
dist: trusty

# Build dependencies.
addons:
  apt:
    packages:
      - libpng-dev
      - libpcre3-dev
      - qtbase5-dev
      - qttools5-dev-tools

# Run the build script.
script: ./travis.sh

notifications:
  irc: "ircs://irc.badnik.zone:6697/#GensGS"
