language: cpp

# Compiler selection.
compiler:
  - clang
  - gcc

# NOTE: Ubuntu 14.04's qttools5-dev-tools is missing FindQt5LinguistTools.cmake.
# However, travis-ci's Ubuntu 16.04 environment doesn't let us install Qt at all,
# so we'll need to use 14.04 with localization disabled for now.
sudo: required
dist: trusty

# Build dependencies.
addons:
  apt:
    packages:
      - libpng-dev
      - libpcre3-dev
      - qtbase5-dev
      - qttools5-dev-tools

# Run the build script.
script: ./travis.sh

notifications:
  irc: "ircs://irc.badnik.zone:6697/#GensGS"
